import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '@component/styles/Home.module.css';
import { Slide } from '../../components/Slide';
import { News } from '../../types/News';
import { SlideMini } from '../../components/Slide copy';
import Introduction from '../../components/Introduction';
import Aos from 'aos';
import 'aos/dist/aos.css';

type Props = {
  items: News[];
}

export default function Home({ items }: Props) {
  const [scrollPosition, setScrollPosition] = useState(0);
  const [top, setTop] = useState(false);

  const handleScroll = () => {
      const position = window.pageYOffset;
      setScrollPosition(position);
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
        window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  useEffect(() => {
    if(scrollPosition >= 1730) {
      setTop(true);
    } else {
      setTop(false);
    }
  }, [scrollPosition]);

  const [w, setW] = useState(false);
  
  useEffect(() => {
    if(typeof window !== "undefined") {
      let s = window.innerWidth;
      if(s > 899) {
        setW(true);
      } else {
        setW(false);
      }
    }
  }, [w]);

  useEffect(() => {
    Aos.init({ duration: 2000 });
  }, []);

  return (
    <>
      <Head>
        <title>Busca Caruaru</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <Slide />
        <Introduction />
        <div className={styles.allNews}>
          <h2 data-aos='fade-up'>Notícias</h2>
          <div data-aos='fade-up' className={styles.adds}>
            <div className={styles.ad1}>
              <h3>Novas regras de trânsito</h3>
              <p>Prefeitura inicia projeto para mudanças de direção em algumas ruas da cidade, segundo o secretário de turismo essa mudança irá diminuir o congestionamento nas vias de acesso aos polos festivos da cidade e aos locais que hoje apresentão maior tráfego nos bairros mais populosos.</p>
            </div>
            <div className={styles.ad2}>
              <h3>Calendário de festas</h3>
              <p>Ministério da Cultura libera o novo calendário para os eventos festivos de 2023. De acordo com o documento, teremos 58 dias de festas que irão dar espaço para apresentações de bandas e grupos de dança nacionais e regionais de diversos ritmos musicais.</p>
            </div>
          </div>
          <div className={styles.body}>
            <div data-aos='fade-up' className={styles.body1}>
              {items.map((item, index)=>(
                <div
                  style={{
                    backgroundImage: `url(${item.image})`
                  }}
                  className={styles.news} key={index}>
                    <h3 data-aos='fade-up'>{item.title}</h3>
                    <p data-aos='fade-up'>{item.text}</p>
                </div>
              ))}
            </div>
            <div style={{
              marginTop: top && w ? scrollPosition - 1730 : 0
            }}>
              <SlideMini />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://my-json-server.typicode.com/LuanGitSilva/api-noticias/data');
  const items: News[] = await res.json();
  
  return { 
      props: { items }, 
      revalidate: 3600 
  }
}
